stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - apps-loadgen  
  - chaos-test
  - cleanup
gcp-cluster:
  image: atulabhi/kops:v8
  stage: cluster-setup
  script: 
    - chmod 775 ./script/gcp
    - ./script/gcp
  artifacts:
    when: always
    paths:
      - .kube/

openebs_gcp_deploy:
  image: atulabhi/kops:v8
  stage: infra-setup
  dependencies:
    - gcp-cluster
  script:
    - echo "Setting up infrastructure"
    - chmod 775 ./script/infra-setup
    - ./script/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

        #percona-jiva:
        #stage: stateful-apps-deploy
        #  image: atulabhi/kops:v8
#  script:
#    - chmod 775 ./script/percona-app-deploy
#    - ./script/percona-app-deploy
#  dependencies:
#    - openebs_gcp_deploy

cassandra-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v8
  script:
    - chmod 775 ./script/cassandra-app-deploy
    - ./script/cassandra-app-deploy
  dependencies:
    - openebs_gcp_deploy

#mongodb-jiva:
#  stage: stateful-apps-deploy
#  image: atulabhi/kops:v8
#  script:
#    - chmod 775 ./script/mongo-app-deploy
#    - ./script/mongo-app-deploy
#  dependencies:
#    - openebs_gcp_deploy

#jenkins-jiva:
#  stage: stateful-apps-deploy
#  image: atulabhi/kops:v8
#  script:
#    - chmod 775 ./script/jenkins-app-deploy
#    - ./script/jenkins-app-deploy
#  dependencies:
#    - openebs_gcp_deploy
#
#postgres-jiva:
#  stage: stateful-apps-deploy
#  image: atulabhi/kops:v8
#  script:
#    - chmod 775 ./script/postgres-app-deploy
#    - ./script/postgres-app-deploy
#  dependencies:
#    - openebs_gcp_deploy

cassandra-loadgen:
  image: atulabhi/kops:v8
  stage: apps-loadgen
  script: 
   - ls -a
   - cat .kube-openebs/config
   - cat ~/.kube/config
   - echo "jobs-Gcp-Started"
   - chmod 775 ./script/cassandra-loadgen
   - ./script/cassandra-loadgen
  dependencies:
   - openebs_gcp_deploy

#mongodb-loadgen:
#  image: atulabhi/kops:v8
#  stage: apps-loadgen
#  script: 
#   - echo "jobs-Gcp-Started"
#   - chmod 775 ./script/mongodb-loadgen
#   - ./script/mongodb-loadgen
#  dependencies:
#   - openebs_gcp_deploy
#
#percona-loadgen:
#  image: atulabhi/kops:v8
#  stage: apps-loadgen
#  script: 
#   - echo "jobs-Gcp-Started"
#   - chmod 775 ./script/percona-loadgen
#   - ./script/percona-loadgen
#  dependencies:
#   - openebs_gcp_deploy
#     
#Litmus-Chaos:
#  stage: chaos-test
#  image: atulabhi/kops:v8
#  script:
#    - chmod 775 ./script/app-chaos
#    - ./script/app-chaos
#  dependencies:
#    - openebs_gcp_deploy

cleanup-gcp:
  image: atulabhi/kops:v8
  dependencies:
    - gcp-cluster
  stage: cleanup
  script: 
    - chmod 775 ./script/gcp-cleanup
    - ./script/gcp-cleanup
  when: always
